
#spring.datasource.url =jdbc:postgresql://localhost:5432/rest_man
#spring.datasource.username=postgres
#spring.datasource.password=123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.application.name=ResturantManagementSystem


# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8081

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/rest_man
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ===============================
# JPA CONFIGURATION
# ===============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT CONFIGURATION (required)
# ===============================

spring.main.allow-circular-references=true
application.security.jwt.secret-key=wZ3Gv7H2eV3Lk8F7A+Q2mC5l0M3pZp7QJHk9Lz1B2Qw=
application.security.jwt.expiration=3600000
application.security.jwt.refresh-token.expiration=86400000



